### PR TITLE
add github actions

### PR DESCRIPTION
**Pull request by knorth55**
this PR adds github actions to build this package in `melodic` and `noetic`.

### CODE REVIEW

**Comment by knorth55** [comment]
Melodic CI build failed, and Noetic CI build passed as expected in #202 .
https://github.com/ros-drivers/usb_cam/actions/runs/4221039793/jobs/7327888750
https://github.com/ros-drivers/usb_cam/actions/runs/4221039793/jobs/7327889141

```
  Errors     << usb_cam:make /root/target_ws/logs/usb_cam/build.make.000.log
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_packet_from_data'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `sws_scale'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_frame_alloc'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_close'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_frame_get_buffer'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_new_packet'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_alloc_context3'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_log_set_level'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_free_context'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_free'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_open2'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_send_packet'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `sws_getContext'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_image_get_buffer_size'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_parser_close'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_parser_init'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_register_all'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `sws_freeContext'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_receive_frame'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `av_image_copy_to_buffer'
  /root/target_ws/devel/.private/usb_cam/lib/libusb_cam.so: undefined reference to `avcodec_find_decoder'
  collect2: error: ld returned 1 exit status
  make[2]: *** [/root/target_ws/devel/.private/usb_cam/lib/usb_cam/usb_cam_node] Error 1
  make[1]: *** [CMakeFiles/usb_cam_node.dir/all] Error 2
  make: *** [all] Error 2
  cd /root/target_ws/build/usb_cam; catkin build --get-env usb_cam | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
  
  
  Failed     << usb_cam:make                         [ Exited with code 2 ]
  Failed    <<< usb_cam                              [ 8.1 seconds ]
```
