### PR TITLE
Fixed build with ffmpeg 3.0

### LINKED ISSUE #48: usb_cam with ffmpeg 3.0 incompatibility
Seems that a few things changes with avcodec/ffmpeg:

> /opt/ros/ros_catkin_ws/src/usb_cam/src/usb_cam.cpp: In member function 'int usb_cam::UsbCam::init_mjpeg_decoder(int, int)':
> /opt/ros/ros_catkin_ws/src/usb_cam/src/usb_cam.cpp:378:41: error: 'avcodec_alloc_frame' was not declared in this scope
>    avframe_camera_ = avcodec_alloc_frame();

full log:
[usb_cam_error.txt](https://github.com/bosch-ros-pkg/usb_cam/files/180980/usb_cam_error.txt)

### PR DESCRIPTION
**Pull request by joshuaeckroth**
Fixes #48. Solution came from @uwesterh and @senden9

### CODE REVIEW

**Comment by svenheitmann** [comment]
The build fails since the job is apparently configured for an older version of ROS (hydro) and Ubuntu (precise) where ffmpeg 2 is used instead of ffmpeg 3.

**Comment by twdragon** [comment]
Closed due to inactivity and FFMPEG API version history.
